# Generated by Django 5.2.7 on 2025-10-19 17:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(max_length=500)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('design', 'Design'), ('development', 'Development'), ('product', 'Product Management')], max_length=20)),
                ('role', models.CharField(max_length=100)),
                ('timeline', models.CharField(max_length=50)),
                ('technologies', models.JSONField(default=list)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.URLField(blank=True, null=True)),
                ('problem_statement', models.TextField()),
                ('solution_overview', models.TextField()),
                ('impact_metrics', models.JSONField(default=list)),
                ('lessons_learned', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_study', to='portfolio.project')),
            ],
            options={
                'verbose_name_plural': 'Case studies',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('section_type', models.CharField(choices=[('research', 'Research'), ('design', 'Design Process'), ('development', 'Development'), ('testing', 'Testing & Validation'), ('results', 'Results & Impact'), ('reflection', 'Reflection')], max_length=20)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('media_urls', models.JSONField(blank=True, default=list)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='portfolio.casestudy')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
