# Generated by Django 5.2.7 on 2025-10-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_audio/'),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_generation_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
