# Generated by Django 5.2.7 on 2025-10-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_message_audio_file_message_audio_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='slide_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='slide_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
