# Generated by Django 5.2.7 on 2025-10-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_add_slide_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response_length',
            field=models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], default='short', max_length=10),
        ),
    ]
