# Generated by Django 5.2.7 on 2025-10-30 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The frequently asked question')),
                ('response', models.TextField(help_text='Plain text response to the question')),
                ('media_urls', models.JSONField(blank=True, default=list, help_text='List of media URLs related to this FAQ (images, videos, etc.)')),
                ('is_featured', models.BooleanField(default=False, blank=True, help_text='Whether the FAQ\'s question is shown as a prompt on the homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this FAQ is active and should be included in LLM context')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority FAQs are included first in LLM context')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
