# Generated by Django 5.2.7 on 2025-10-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='faq_audio/'),
        ),
        migrations.AddField(
            model_name='faq',
            name='audio_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='audio_generation_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
