# Generated by Django 5.2.7 on 2025-10-30 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_faq_audio_file_faq_audio_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='source_faq',
            field=models.ForeignKey(blank=True, help_text='FAQ that was used as the source for this response', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.faq'),
        ),
    ]
