# Generated by Django 5.2.7 on 2025-11-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_message_source_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudy',
            old_name='problem_statement',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='impact_metrics',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='lessons_learned',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='next_steps',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='solution_overview',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='category',
            field=models.CharField(choices=[('design', 'Design'), ('development', 'Development'), ('ux_engineering', 'UX Engineering'), ('product', 'Product Management')], max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('overview', 'Overview'), ('context', 'Context'), ('research', 'Research & Discovery'), ('design', 'Design Process'), ('implementation', 'Implementation'), ('results', 'Results & Impact'), ('reflection', 'Reflection')], max_length=20),
        ),
    ]
