# Generated by Django 5.2.7 on 2025-11-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_rename_problem_statement_casestudy_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='slide_media_urls',
            field=models.JSONField(blank=True, default=list, help_text='Media URLs for slide carousel'),
        ),
    ]
