# Generated by Django 5.2.7 on 2025-11-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_message_slide_media_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='audio_word_timestamps',
            field=models.JSONField(blank=True, default=list, help_text='Word-level timestamps for audio synchronization'),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_word_timestamps',
            field=models.JSONField(blank=True, default=list, help_text='Word-level timestamps for audio synchronization'),
        ),
    ]
