# Generated by Django 5.2.7 on 2025-11-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_faq_audio_word_timestamps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='follow_up_suggestions',
            field=models.JSONField(blank=True, default=list, help_text='Follow-up questions suggested by the AI'),
        ),
    ]
