# Generated by Django 5.2.7 on 2025-11-03 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_message_follow_up_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_studies', to='portfolio.project'),
        ),
    ]
