# Generated by Django 5.2.7 on 2025-11-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_casestudy_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='context',
            field=models.TextField(blank=True, default=''),
        ),
    ]
